### ISSUE TITLE
Bug Tracker

### ISSUE THREAD

**Issue by BarraSantiago** [Okami115/Kometes#1]
-no hay aceleración
-no se modifica la dirección de la nave si se mantiene el click derecho apretado
-pueden spawnear asteroides encima tuyo
-la nave roja no despawnea cuando recibís daño
-en el git hay archivos que se regeneran (tipo el bin)

**Comment by Okami115** [comment]
- Si hay aceleración, pero es muy bruta apropósito.
- No se modifica mientras se mantiene el click para sumarle algo de dificultad y tener que estar pendiente de dar 2 click en distintos lugares.
- No pueden spawnear asteroides arriba tuyo ya que todos los asteroides "Nuevos" viene de las esquinas de la pantalla, en todo caso cuando un cometa se parte y estas muy cerca puede que colisione con la nave.
-  Y la mecanica diferencial de la nave roja es que la tenes que romper lo antes posible ya que ni los powerUps pueden romperla.
